repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: mixed-line-ending
      - id: detect-aws-credentials
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-symlinks
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-added-large-files
        args: ["--maxkb=500"]
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: 3701d2cb65198ec748d3a593628625be9f91fe27  # frozen: v2.3.1
    hooks:
      - id: stylua-github
